# Generated by Django 5.1.2 on 2024-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_token_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_SM', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('participants', models.IntegerField()),
                ('age_group', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
