# Generated by Django 5.1.2 on 2024-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
