# Generated by Django 5.1.2 on 2024-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_usertoken_key_usertoken_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='id',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='key',
            field=models.CharField(default=1, max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
