# Generated by Django 5.1.3 on 2024-11-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='citation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
