# Generated by Django 5.1.3 on 2024-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quote_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='citation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
